### ISSUE TITLE
[BACKLOG] Peers

### ISSUE THREAD

**Issue by julianknutsen** [rust-bitcoin/rust-lightning#707]
Meta issue containing work items for the ln/peers module. Items are in rough priority order and will change over time.

**Ready for Work**
- [ ] [[Peers] Add doc/transport_module.md](https://github.com/rust-bitcoin/rust-lightning/issues/706)
- [ ] [[Peers] Tech Debt: Move Transport code to separate folder](https://github.com/rust-bitcoin/rust-lightning/issues/704)
- [ ] [[Peers] Tech Debt: Rename node_id/their_node_id](https://github.com/rust-bitcoin/rust-lightning/issues/705)
- [ ] [[Peers] Testing: Simplify unit tests of the event handling code](https://github.com/rust-bitcoin/rust-lightning/issues/697)
- [ ] [[Peers] Testing: Simplify unit tests of the message handling code](https://github.com/rust-bitcoin/rust-lightning/issues/698)
- [ ] [[Peers] Testing: Unit test PeerHolder](https://github.com/rust-bitcoin/rust-lightning/issues/699)
- [ ] [[Peers] Security: Initialize act data buffer with random data](https://github.com/rust-bitcoin/rust-lightning/issues/700) 
- [ ] [[Peers] Feature: Send message contained in ErrorAction::DisconnectPeer](https://github.com/rust-bitcoin/rust-lightning/issues/701)
- [ ] [[Peers] Feature: Add Channel/Node/Update forwarding](https://github.com/rust-bitcoin/rust-lightning/issues/702)
- [ ] [[Peers] Feature: Implement optional message dropping in Message send path](https://github.com/rust-bitcoin/rust-lightning/issues/703)

**Need Refinement**

**Comment by ariard** [comment]
Extend unit test coverage once gossips are further integrated in peers code. See https://github.com/rust-bitcoin/rust-lightning/pull/736#issuecomment-720610489 for more information.
